# Generated by Django 5.1 on 2024-09-20 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_class', models.CharField(max_length=50)),
                ('offense_description', models.TextField()),
                ('offense_date', models.DateField()),
                ('witness_name', models.CharField(max_length=255)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_class', models.CharField(blank=True, max_length=50, null=True)),
                ('care_given_to_victim', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Discipline', 'Discipline'), ('Bullying', 'Bullying'), ('Incident', 'Incident'), ('Accident', 'Accident')], max_length=50)),
                ('sanction', models.CharField(max_length=255)),
                ('parent_notified', models.BooleanField(default=False)),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_details', models.TextField()),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='committee.studentoffense')),
            ],
        ),
    ]
